export const authConstants = {
    LOGIN_REQUEST:"LOGIN_REQUEST",
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    LOGIN_FAILURE : "LOGIN_FAILURE",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS:"LOGOUT_SUCCESS",
    LOGOUT_FAILURE :"LOGOUT_FAILURE"
}

export const userConstants = {
    SIGNUP_REQUEST:"SIGNUP_REQUEST",
    SIGNUP_SUCCESS:"SIGNUP_SUCCESS",
    SIGNUP_FAILURE :"SIGNUP_FAILURE"
} 

export const todoConstants = {
    GET_TODO_REQUEST : "GET_TODO_REQUEST",
    GET_TODO_SUCCESS : "GET_TODO_SUCCESS",
    GET_TODO_FAILURE : "GET_TODO_FAILURE",
    ADD_TODO_REQUEST : "ADD_TODO_REQUEST",
    ADD_TODO_SUCCESS : "ADD_TODO_SUCCESS",
    ADD_TODO_FAILURE : "ADD_TODO_FAILURE",
    REMOVE_TODO_REQUEST : "REMOVE_TODO_REQUEST",
    REMOVE_TODO_SUCCESS : "REMOVE_TODO_SUCCESS",
    REMOVE_TODO_FAILURE : "REMOVE_TODO_FAILURE"
}